version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: auth_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: auth_service
    ports:
      - "55432:5432" # Mapea el puerto de tu máquina al puerto del contenedor
    volumes:
      - pgdata:/var/lib/postgresql/data # Guarda los datos de forma persistente
    command: postgres -c password_encryption=md5

  redis:
    image: redis:latest
    container_name: mi_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth_service_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

volumes:
  pgdata:
  redisdata: